spring.application.name=car-dealership
spring.datasource.url=${jdbc:mysql://localhost:3306/car_dealer}
spring.datasource.username=${root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${mysecretkeymysecretkeymysecretkey123456789}
server.port=${PORT:8080}

#spring.datasource.url=jdbc:mysql://localhost:3306/car_dealer
#
#spring.datasource.username=root
#
#
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true